/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2025-03-10 09:37:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1741583255460L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1741459548044L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

   

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Pragnya</title>\r\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\"></link>\r\n");
      out.write("<style>\r\n");
      out.write(".logo-img {\r\n");
      out.write("	transform: rotate(180deg);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header class=\"bg-white shadow\">\r\n");
      out.write("		<div class=\"container mx-auto p-4 flex justify-between items-center\">\r\n");
      out.write("			<div class=\"flex items-center space-x-4\">\r\n");
      out.write("				<img class=\"logo-img\"\r\n");
      out.write("					alt=\"Pragnya logo with a stylized book and graduation cap\"\r\n");
      out.write("					class=\"h-12 w-12\" height=\"50\" src=\"pragya.png\" width=\"50\" />\r\n");
      out.write("				<h1 class=\"text-2xl font-bold\">Pragnya</h1>\r\n");
      out.write("			</div>\r\n");
      out.write("			<nav class=\"hidden md:flex space-x-4 items-center\">\r\n");
      out.write("				<a href=\"#welcome\" class=\"text-gray-700 hover:text-blue-500\">Home</a>\r\n");
      out.write("				<a href=\"#about\" class=\"text-gray-700 hover:text-blue-500\">About\r\n");
      out.write("					Us</a> <a href=\"#popular-courses\"\r\n");
      out.write("					class=\"text-gray-700 hover:text-blue-500\">Popular Courses</a> <a\r\n");
      out.write("					href=\"#feedback\" class=\"text-gray-700 hover:text-blue-500\">Feedback</a>\r\n");
      out.write("				<div class=\"relative\">\r\n");
      out.write("					<input type=\"text\" placeholder=\"Explore...\"\r\n");
      out.write("						class=\"border border-gray-300 rounded-lg px-4 py-2\" />\r\n");
      out.write("					<button class=\"absolute right-0 top-0 mt-2 mr-2 text-gray-500\">\r\n");
      out.write("						<i class=\"fas fa-search\"></i>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"relative\">\r\n");
      out.write("					<button\r\n");
      out.write("						class=\"text-gray-700 hover:text-blue-500 flex items-center w-full\">\r\n");
      out.write("						<i class=\"fas fa-user mr-2\"> </i> Login\r\n");
      out.write("					</button>\r\n");
      out.write("					<!--  		<a href=\"login\"\r\n");
      out.write("						class=\"text-gray-700 hover:text-blue-500 flex items-center w-full\">\r\n");
      out.write("						<i class=\"fas fa-user mr-2\"></i> Login\r\n");
      out.write("					</a>-->\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<div class=\"md:hidden\">\r\n");
      out.write("				<button id=\"mobile-menu-button\"\r\n");
      out.write("					class=\"text-gray-700 hover:text-blue-500\">\r\n");
      out.write("					<i class=\"fas fa-bars\"></i>\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"mobile-menu-dropdown\" class=\"hidden bg-white shadow-lg\">\r\n");
      out.write("			<nav class=\"space-y-2 p-4\">\r\n");
      out.write("				<a href=\"#welcome\" class=\"block text-gray-700 hover:text-blue-500\">Home</a>\r\n");
      out.write("				<a href=\"#about\" class=\"block text-gray-700 hover:text-blue-500\">About\r\n");
      out.write("					Us</a> <a href=\"#popular-courses\"\r\n");
      out.write("					class=\"block text-gray-700 hover:text-blue-500\">Popular Courses</a>\r\n");
      out.write("				<a href=\"#feedback\" class=\"block text-gray-700 hover:text-blue-500\">Feedback</a>\r\n");
      out.write("				<div class=\"relative\">\r\n");
      out.write("					<input type=\"text\" placeholder=\"Explore...\"\r\n");
      out.write("						class=\"border border-gray-300 rounded-lg px-4 py-2 w-full\" />\r\n");
      out.write("					<button class=\"absolute right-0 top-0 mt-2 mr-2 text-gray-500\">\r\n");
      out.write("						<i class=\"fas fa-search\"></i>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<button class=\"text-gray-700 hover:text-blue-500 flex items-center\">\r\n");
      out.write("					<i class=\"fas fa-user mr-2\"></i> <a href=\"login.html\">Login</a>\r\n");
      out.write("				</button>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		document.getElementById('mobile-menu-button').addEventListener('click',\r\n");
      out.write("				function() {\r\n");
      out.write("					var menu = document.getElementById('mobile-menu-dropdown');\r\n");
      out.write("					if (menu.classList.contains('hidden')) {\r\n");
      out.write("						menu.classList.remove('hidden');\r\n");
      out.write("					} else {\r\n");
      out.write("						menu.classList.add('hidden');\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write(" <head>\r\n");
      out.write("  <meta charset=\"utf-8\"/>\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"/>\r\n");
      out.write("  <title>\r\n");
      out.write("   Pragnya - Learning Management System\r\n");
      out.write("  </title>\r\n");
      out.write("  <script src=\"https://cdn.tailwindcss.com\">\r\n");
      out.write("  </script>\r\n");
      out.write("  <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&amp;display=swap\" rel=\"stylesheet\"/>\r\n");
      out.write("  <style>\r\n");
      out.write("   body {\r\n");
      out.write("            font-family: 'Roboto', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        .carousel {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        .carousel-inner {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            transition: transform 0.5s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("        .carousel-item {\r\n");
      out.write("            min-width: 100%;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        .carousel-control-prev, .carousel-control-next {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            transform: translateY(-50%);\r\n");
      out.write("            background-color: rgba(0, 0, 0, 0.5);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .carousel-control-prev {\r\n");
      out.write("            left: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .carousel-control-next {\r\n");
      out.write("            right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .mobile-menu {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        .logo-img{\r\n");
      out.write("            transform: rotate(180deg);\r\n");
      out.write("        }\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .desktop-menu {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("            .mobile-menu {\r\n");
      out.write("                display: block;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("  </style>\r\n");
      out.write("  <script>\r\n");
      out.write("  /*  function loadNavbar() {\r\n");
      out.write("        fetch(\"navbar.html\")\r\n");
      out.write("            .then(response => response.text())\r\n");
      out.write("            .then(data => {\r\n");
      out.write("                document.getElementById(\"navbar-container\").innerHTML = data;\r\n");
      out.write("            })\r\n");
      out.write("            .catch(error => console.error(\"Error loading navbar:\", error));\r\n");
      out.write("    }\r\n");
      out.write("    window.onload = loadNavbar;*/\r\n");
      out.write("</script>\r\n");
      out.write(" </head>\r\n");
      out.write(" <body class=\"bg-gray-100\">\r\n");
      out.write("  <header class=\"bg-white shadow\">\r\n");
      out.write("    <div id=\"navbar-container\"></div>\r\n");
      out.write("    <!---\r\n");
      out.write("   <div class=\"container mx-auto p-4 flex justify-between items-center\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"flex items-center space-x-4\">\r\n");
      out.write("     <img class = \"logo-img\"alt=\"Pragnya logo with a stylized book and graduation cap\" class=\"h-12 w-12\" height=\"50\" src=\"pragya.png\" width=\"50\"/>\r\n");
      out.write("     <h1 class=\"text-2xl font-bold\">\r\n");
      out.write("      Pragnya\r\n");
      out.write("     </h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav class=\"space-x-4 flex items-center desktop-menu\">\r\n");
      out.write("     <a class=\"text-gray-700 hover:text-blue-500\" href=\"#welcome\">\r\n");
      out.write("      Home\r\n");
      out.write("     </a>\r\n");
      out.write("     <a class=\"text-gray-700 hover:text-blue-500\" href=\"#about\">\r\n");
      out.write("      About Us\r\n");
      out.write("     </a>\r\n");
      out.write("     <a class=\"text-gray-700 hover:text-blue-500\" href=\"#popular-courses\">\r\n");
      out.write("      Popular Courses\r\n");
      out.write("     </a>\r\n");
      out.write("     <a class=\"text-gray-700 hover:text-blue-500\" href=\"#feedback\">\r\n");
      out.write("      Feedback\r\n");
      out.write("     </a>\r\n");
      out.write("     <div class=\"relative\">\r\n");
      out.write("      <input class=\"border border-gray-300 rounded-lg px-4 py-2\" placeholder=\"Explore...\" type=\"text\"/>\r\n");
      out.write("      <button class=\"absolute right-0 top-0 mt-2 mr-2 text-gray-500\">\r\n");
      out.write("       <i class=\"fas fa-search\">\r\n");
      out.write("       </i>\r\n");
      out.write("      </button>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"relative\">\r\n");
      out.write("      <button class=\"text-gray-700 hover:text-blue-500 flex items-center\">\r\n");
      out.write("       <i class=\"fas fa-user mr-2\">\r\n");
      out.write("       </i>\r\n");
      out.write("       <a href=\"login.html\">\r\n");
      out.write("       Login\r\n");
      out.write("       </a>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"absolute right-0 mt-2 w-48 bg-white border border-gray-200 rounded-lg shadow-lg hidden group-hover:block\">\r\n");
      out.write("       <a class=\"block px-4 py-2 text-gray-700 hover:bg-gray-100\" href=\"instructor/login.jsp\">\r\n");
      out.write("        Instructor Login\r\n");
      out.write("       </a>\r\n");
      out.write("       <a class=\"block px-4 py-2 text-gray-700 hover:bg-gray-100\" href=\"student/login.jsp\">\r\n");
      out.write("        Student Login\r\n");
      out.write("       </a>\r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("    </nav>------>\r\n");
      out.write(" <!-- -  <div class=\"mobile-menu\">\r\n");
      out.write("     <button id=\"mobile-menu-button\" class=\"text-gray-700 hover:text-blue-500\">\r\n");
      out.write("      <i class=\"fas fa-bars\"></i>\r\n");
      out.write("     </button>\r\n");
      out.write("    </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"mobile-menu-dropdown\" class=\"hidden bg-white shadow-lg\">\r\n");
      out.write("    <nav class=\"space-y-2 p-4\">\r\n");
      out.write("     <a class=\"block text-gray-700 hover:text-blue-500\" href=\"#welcome\">\r\n");
      out.write("      Home\r\n");
      out.write("     </a>\r\n");
      out.write("     <a class=\"block text-gray-700 hover:text-blue-500\" href=\"#about\">\r\n");
      out.write("      About Us\r\n");
      out.write("     </a>\r\n");
      out.write("     <a class=\"block text-gray-700 hover:text-blue-500\" href=\"#popular-courses\">\r\n");
      out.write("      Popular Courses\r\n");
      out.write("     </a>\r\n");
      out.write("     <a class=\"block text-gray-700 hover:text-blue-500\" href=\"#feedback\">\r\n");
      out.write("      Feedback\r\n");
      out.write("     </a>\r\n");
      out.write("     <div class=\"relative\">\r\n");
      out.write("      <input class=\"border border-gray-300 rounded-lg px-4 py-2 w-full\" placeholder=\"Explore...\" type=\"text\"/>\r\n");
      out.write("      <button class=\"absolute right-0 top-0 mt-2 mr-2 text-gray-500\">\r\n");
      out.write("       <i class=\"fas fa-search\">\r\n");
      out.write("       </i>\r\n");
      out.write("      </button>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"relative\">\r\n");
      out.write("      <button class=\"text-gray-700 hover:text-blue-500 flex items-center w-full\">\r\n");
      out.write("       <i class=\"fas fa-user mr-2\">\r\n");
      out.write("       </i>\r\n");
      out.write("       Login\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"absolute right-0 mt-2 w-48 bg-white border border-gray-200 rounded-lg shadow-lg hidden group-hover:block\">\r\n");
      out.write("       <a class=\"block px-4 py-2 text-gray-700 hover:bg-gray-100\" href=\"instructor/login.jsp\">\r\n");
      out.write("        Instructor Login\r\n");
      out.write("       </a>\r\n");
      out.write("       <a class=\"block px-4 py-2 text-gray-700 hover:bg-gray-100\" href=\"student/login.jsp\">\r\n");
      out.write("        Student Login\r\n");
      out.write("       </a>\r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("    </nav>  --> \r\n");
      out.write("   </div>\r\n");
      out.write("  </header>\r\n");
      out.write("  <main class=\"container mx-auto p-4\">\r\n");
      out.write("   <section id=\"welcome\" class=\"text-center mb-12\">\r\n");
      out.write("    <h2 class=\"text-4xl font-bold mb-4\">\r\n");
      out.write("     Welcome to Pragnya\r\n");
      out.write("    </h2>\r\n");
      out.write("    <p class=\"text-gray-600 mb-8\">\r\n");
      out.write("     Empowering Instructors and Students with a seamless learning experience.\r\n");
      out.write("    </p>\r\n");
      out.write("    <div class=\"carousel\">\r\n");
      out.write("     <div class=\"carousel-inner\">\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("       <img alt=\"Image 1 description\" class=\"w-full h-64 object-cover\" height=\"400\" src=\"https://storage.googleapis.com/a1aa/image/zZQOv_DPW75Z_FwVoOH_fSAEd0hGDr5kjWs6Ryp9vFw.jpg\" width=\"800\"/>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("       <img alt=\"Image 2 description\" class=\"w-full h-64 object-cover\" height=\"400\" src=\"https://storage.googleapis.com/a1aa/image/mkacrP6MrUuCVk0z_sGuBC-gRYY1Na7pf7WB3Ykhb4g.jpg\" width=\"800\"/>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("       <img alt=\"Image 3 description\" class=\"w-full h-64 object-cover\" height=\"400\" src=\"https://storage.googleapis.com/a1aa/image/XTHbDaduRUSXggDg5O4TbLhFBII1tGe5Uq0co5RjdN4.jpg\" width=\"800\"/>\r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <button class=\"carousel-control-prev\" onclick=\"prevSlide()\">\r\n");
      out.write("      â®\r\n");
      out.write("     </button>\r\n");
      out.write("     <button class=\"carousel-control-next\" onclick=\"nextSlide()\">\r\n");
      out.write("      â¯\r\n");
      out.write("     </button>\r\n");
      out.write("    </div>\r\n");
      out.write("   </section>\r\n");
      out.write("   <section id=\"about\" class=\"text-center mb-12\">\r\n");
      out.write("    <h2 class=\"text-3xl font-bold mb-4\">\r\n");
      out.write("     About Us\r\n");
      out.write("    </h2>\r\n");
      out.write("    <p class=\"text-gray-600 mb-8\">\r\n");
      out.write("     Pragnya is dedicated to providing the best online learning experience for both instructors and students. Our platform offers a wide range of courses, interactive learning tools, and real-time feedback to ensure a seamless and effective learning journey.\r\n");
      out.write("    </p>\r\n");
      out.write("   </section>\r\n");
      out.write("   <section id=\"popular-courses\" class=\"mt-12 text-center\">\r\n");
      out.write("    <h2 class=\"text-3xl font-bold mb-4\">\r\n");
      out.write("     Popular Courses\r\n");
      out.write("    </h2>\r\n");
      out.write("    <div class=\"carousel relative\">\r\n");
      out.write("     <div class=\"carousel-inner\">\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("       <div class=\"grid grid-cols-1 md:grid-cols-3 gap-8\">\r\n");
      out.write("        <div class=\"bg-white p-6 rounded-lg shadow-lg\">\r\n");
      out.write("         <img alt=\"Course 1 illustration\" class=\"w-full h-40 object-cover mb-4 rounded\" height=\"200\" src=\"https://storage.googleapis.com/a1aa/image/oCQ2dfUeSnBhsPBQC4yaOp6tYd0YhEYf3PCYTA_u6k4.jpg\" width=\"300\"/>\r\n");
      out.write("         <h3 class=\"text-xl font-bold mb-2\">\r\n");
      out.write("          Course Title 1\r\n");
      out.write("         </h3>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          Brief description of the course content and objectives.\r\n");
      out.write("         </p>\r\n");
      out.write("         <a class=\"bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition duration-300\" href=\"#\">\r\n");
      out.write("          Enroll Now\r\n");
      out.write("         </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bg-white p-6 rounded-lg shadow-lg\">\r\n");
      out.write("         <img alt=\"Course 2 illustration\" class=\"w-full h-40 object-cover mb-4 rounded\" height=\"200\" src=\"https://storage.googleapis.com/a1aa/image/w0MERh0QgDb7jG27A_K1L7OFgWjsqTlmg1SThgbUvA8.jpg\" width=\"300\"/>\r\n");
      out.write("         <h3 class=\"text-xl font-bold mb-2\">\r\n");
      out.write("          Course Title 2\r\n");
      out.write("         </h3>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          Brief description of the course content and objectives.\r\n");
      out.write("         </p>\r\n");
      out.write("         <a class=\"bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition duration-300\" href=\"#\">\r\n");
      out.write("          Enroll Now\r\n");
      out.write("         </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bg-white p-6 rounded-lg shadow-lg\">\r\n");
      out.write("         <img alt=\"Course 3 illustration\" class=\"w-full h-40 object-cover mb-4 rounded\" height=\"200\" src=\"https://storage.googleapis.com/a1aa/image/lJPTL8pR09dgJqtvBUX8H4oW5DdMVDUd9rgQaNz15Io.jpg\" width=\"300\"/>\r\n");
      out.write("         <h3 class=\"text-xl font-bold mb-2\">\r\n");
      out.write("          Course Title 3\r\n");
      out.write("         </h3>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          Brief description of the course content and objectives.\r\n");
      out.write("         </p>\r\n");
      out.write("         <a class=\"bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition duration-300\" href=\"#\">\r\n");
      out.write("          Enroll Now\r\n");
      out.write("         </a>\r\n");
      out.write("        </div>\r\n");
      out.write("       </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("       <div class=\"grid grid-cols-1 md:grid-cols-3 gap-8\">\r\n");
      out.write("        <div class=\"bg-white p-6 rounded-lg shadow-lg\">\r\n");
      out.write("         <img alt=\"Course 4 illustration\" class=\"w-full h-40 object-cover mb-4 rounded\" height=\"200\" src=\"https://storage.googleapis.com/a1aa/image/4.jpg\" width=\"300\"/>\r\n");
      out.write("         <h3 class=\"text-xl font-bold mb-2\">\r\n");
      out.write("          Course Title 4\r\n");
      out.write("         </h3>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          Brief description of the course content and objectives.\r\n");
      out.write("         </p>\r\n");
      out.write("         <a class=\"bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition duration-300\" href=\"#\">\r\n");
      out.write("          Enroll Now\r\n");
      out.write("         </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bg-white p-6 rounded-lg shadow-lg\">\r\n");
      out.write("         <img alt=\"Course 5 illustration\" class=\"w-full h-40 object-cover mb-4 rounded\" height=\"200\" src=\"https://storage.googleapis.com/a1aa/image/5.jpg\" width=\"300\"/>\r\n");
      out.write("         <h3 class=\"text-xl font-bold mb-2\">\r\n");
      out.write("          Course Title 5\r\n");
      out.write("         </h3>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          Brief description of the course content and objectives.\r\n");
      out.write("         </p>\r\n");
      out.write("         <a class=\"bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition duration-300\" href=\"#\">\r\n");
      out.write("          Enroll Now\r\n");
      out.write("         </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bg-white p-6 rounded-lg shadow-lg\">\r\n");
      out.write("         <img alt=\"Course 6 illustration\" class=\"w-full h-40 object-cover mb-4 rounded\" height=\"200\" src=\"https://storage.googleapis.com/a1aa/image/6.jpg\" width=\"300\"/>\r\n");
      out.write("         <h3 class=\"text-xl font-bold mb-2\">\r\n");
      out.write("          Course Title 6\r\n");
      out.write("         </h3>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          Brief description of the course content and objectives.\r\n");
      out.write("         </p>\r\n");
      out.write("         <a class=\"bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition duration-300\" href=\"#\">\r\n");
      out.write("          Enroll Now\r\n");
      out.write("         </a>\r\n");
      out.write("        </div>\r\n");
      out.write("       </div>\r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <button class=\"carousel-control-next\" onclick=\"nextCourseSlide()\">\r\n");
      out.write("      â¯\r\n");
      out.write("     </button>\r\n");
      out.write("    </div>\r\n");
      out.write("   </section>\r\n");
      out.write("   <section id=\"feedback\" class=\"mt-12 text-center\">\r\n");
      out.write("    <h2 class=\"text-3xl font-bold mb-4\">\r\n");
      out.write("     Course Feedback\r\n");
      out.write("    </h2>\r\n");
      out.write("    <div class=\"carousel relative\">\r\n");
      out.write("     <div class=\"carousel-inner\">\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("       <div class=\"grid grid-cols-1 md:grid-cols-3 gap-8\">\r\n");
      out.write("        <div class=\"bg-white p-6 rounded-lg shadow-lg\">\r\n");
      out.write("         <h3 class=\"text-xl font-bold mb-2\">\r\n");
      out.write("          Course Title 1\r\n");
      out.write("         </h3>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          \"This course was very informative and well-structured. The instructor was knowledgeable and engaging.\"\r\n");
      out.write("         </p>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          \"I learned a lot from this course. The materials were easy to follow and the assignments were challenging but manageable.\"\r\n");
      out.write("         </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bg-white p-6 rounded-lg shadow-lg\">\r\n");
      out.write("         <h3 class=\"text-xl font-bold mb-2\">\r\n");
      out.write("          Course Title 2\r\n");
      out.write("         </h3>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          \"The course content was up-to-date and relevant. The instructor provided great examples and real-world applications.\"\r\n");
      out.write("         </p>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          \"I appreciated the interactive elements of this course. The quizzes and discussions helped reinforce the material.\"\r\n");
      out.write("         </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bg-white p-6 rounded-lg shadow-lg\">\r\n");
      out.write("         <h3 class=\"text-xl font-bold mb-2\">\r\n");
      out.write("          Course Title 3\r\n");
      out.write("         </h3>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          \"This course exceeded my expectations. The instructor was very supportive and provided valuable feedback.\"\r\n");
      out.write("         </p>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          \"I highly recommend this course to anyone looking to expand their knowledge in this field. The resources provided were excellent.\"\r\n");
      out.write("         </p>\r\n");
      out.write("        </div>\r\n");
      out.write("       </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("       <div class=\"grid grid-cols-1 md:grid-cols-3 gap-8\">\r\n");
      out.write("        <div class=\"bg-white p-6 rounded-lg shadow-lg\">\r\n");
      out.write("         <h3 class=\"text-xl font-bold mb-2\">\r\n");
      out.write("          Course Title 4\r\n");
      out.write("         </h3>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          \"The course was well-organized and the instructor was very knowledgeable.\"\r\n");
      out.write("         </p>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          \"I found the course content to be very relevant and up-to-date.\"\r\n");
      out.write("         </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bg-white p-6 rounded-lg shadow-lg\">\r\n");
      out.write("         <h3 class=\"text-xl font-bold mb-2\">\r\n");
      out.write("          Course Title 5\r\n");
      out.write("         </h3>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          \"The instructor provided great examples and real-world applications.\"\r\n");
      out.write("         </p>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          \"I appreciated the interactive elements of this course.\"\r\n");
      out.write("         </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bg-white p-6 rounded-lg shadow-lg\">\r\n");
      out.write("         <h3 class=\"text-xl font-bold mb-2\">\r\n");
      out.write("          Course Title 6\r\n");
      out.write("         </h3>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          \"This course exceeded my expectations.\"\r\n");
      out.write("         </p>\r\n");
      out.write("         <p class=\"text-gray-600 mb-4\">\r\n");
      out.write("          \"The instructor was very supportive and provided valuable feedback.\"\r\n");
      out.write("         </p>\r\n");
      out.write("        </div>\r\n");
      out.write("       </div>\r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <button class=\"carousel-control-next\" onclick=\"nextFeedbackSlide()\">\r\n");
      out.write("      â¯\r\n");
      out.write("     </button>\r\n");
      out.write("    </div>\r\n");
      out.write("   </section>\r\n");
      out.write("   <section class=\"mt-12 text-center\">\r\n");
      out.write("    <h2 class=\"text-3xl font-bold mb-4\">\r\n");
      out.write("     Manage Your Learning\r\n");
      out.write("    </h2>\r\n");
      out.write("    <div class=\"flex justify-center space-x-4\">\r\n");
      out.write("     <a class=\"bg-yellow-500 text-white px-6 py-3 rounded-lg shadow-lg hover:bg-yellow-600 transition duration-300\" href=\"dashboard.jsp\">\r\n");
      out.write("      <i class=\"fas fa-tachometer-alt mr-2\">\r\n");
      out.write("      </i>\r\n");
      out.write("      Course Dashboard\r\n");
      out.write("     </a>\r\n");
      out.write("     <a class=\"bg-purple-500 text-white px-6 py-3 rounded-lg shadow-lg hover:bg-purple-600 transition duration-300\" href=\"feedback.jsp\">\r\n");
      out.write("      <i class=\"fas fa-star mr-2\">\r\n");
      out.write("      </i>\r\n");
      out.write("      Feedback System\r\n");
      out.write("     </a>\r\n");
      out.write("    </div>\r\n");
      out.write("   </section>\r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Footer</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/YOUR_KIT_CODE.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <footer class=\"bg-gray-800 text-white py-8\">\r\n");
      out.write("        <div class=\"container mx-auto grid grid-cols-1 md:grid-cols-3 gap-8\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <h3 class=\"text-xl font-bold mb-4\">About Us</h3>\r\n");
      out.write("                <p class=\"text-gray-400\">We are dedicated to providing the best online learning experience for both instructors and students.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <h3 class=\"text-xl font-bold mb-4\">Quick Links</h3>\r\n");
      out.write("                <ul class=\"text-gray-400\">\r\n");
      out.write("                    <li class=\"mb-2\"><a class=\"hover:text-white\" href=\"#\">Home</a></li>\r\n");
      out.write("                    <li class=\"mb-2\"><a class=\"hover:text-white\" href=\"#\">Courses</a></li>\r\n");
      out.write("                    <li class=\"mb-2\"><a class=\"hover:text-white\" href=\"#\">About</a></li>\r\n");
      out.write("                    <li class=\"mb-2\"><a class=\"hover:text-white\" href=\"#\">Contact</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <h3 class=\"text-xl font-bold mb-4\">Contact Us</h3>\r\n");
      out.write("                <p class=\"text-gray-400 mb-2\"><i class=\"fas fa-envelope mr-2\"></i> info@pragnya.com</p>\r\n");
      out.write("                <p class=\"text-gray-400 mb-2\"><i class=\"fas fa-phone mr-2\"></i> +1 234 567 890</p>\r\n");
      out.write("                <p class=\"text-gray-400\"><i class=\"fas fa-map-marker-alt mr-2\"></i> 123 Pragnya Street, Education City, USA</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container mx-auto text-center mt-8\">\r\n");
      out.write("            <p>Â© 2023 Pragnya. All rights reserved.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
