/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2025-03-10 10:29:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insdashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbardashboard.jsp", Long.valueOf(1741521367525L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1741459548044L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String role = (String) session.getAttribute("role");
    if (role == null || !role.equals("INSTRUCTOR")) {
        response.sendRedirect("login.jsp");
        return;
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	    if (session.getAttribute("role") == null) {
	        response.sendRedirect("login.jsp");
	        return;
	    }
	
	    // Invalidate session on refresh
	    session.invalidate();
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Pragnya</title>\r\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\">\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<style>\r\n");
      out.write(".logo-img {\r\n");
      out.write("	transform: rotate(180deg);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header class=\"bg-white shadow\">\r\n");
      out.write("		<div class=\"container mx-auto p-4 flex justify-between items-center\">\r\n");
      out.write("			<div class=\"flex items-center space-x-4\">\r\n");
      out.write("				<img alt=\"Pragnya logo with a stylized book and graduation cap\"\r\n");
      out.write("					class=\"logo-img\" height=\"50\" src=\"pragya.png\" width=\"50\" />\r\n");
      out.write("				<h1 class=\"text-2xl font-bold\">Pragnya</h1>\r\n");
      out.write("			</div>\r\n");
      out.write("			<nav class=\"hidden md:flex space-x-4 items-center\">\r\n");
      out.write("				<a class=\"text-gray-700 hover:text-blue-500\" href=\"#welcome\">\r\n");
      out.write("					Home </a> <a class=\"text-gray-700 hover:text-blue-500\" href=\"#about\">\r\n");
      out.write("					About Us </a> <a class=\"text-gray-700 hover:text-blue-500\"\r\n");
      out.write("					href=\"#popular-courses\"> Popular Courses </a> <a\r\n");
      out.write("					class=\"text-gray-700 hover:text-blue-500\" href=\"#feedback\">\r\n");
      out.write("					Feedback </a>\r\n");
      out.write("				<div class=\"relative\">\r\n");
      out.write("					<input class=\"border border-gray-300 rounded-lg px-4 py-2\"\r\n");
      out.write("						placeholder=\"Explore...\" type=\"text\" />\r\n");
      out.write("					<button class=\"absolute right-0 top-0 mt-2 mr-2 text-gray-500\">\r\n");
      out.write("						<i class=\"fas fa-search\"> </i>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"relative\">\r\n");
      out.write("					<a href=\"logout.jsp\"\r\n");
      out.write("						class=\"bg-red-500 text-white px-4 py-2 rounded-lg hover:bg-red-600 flex items-center\">\r\n");
      out.write("						<i class=\"fas fa-sign-out-alt mr-2\"></i> Logout\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<div class=\"md:hidden\">\r\n");
      out.write("				<button class=\"text-gray-700 hover:text-blue-500\"\r\n");
      out.write("					id=\"mobile-menu-button\">\r\n");
      out.write("					<i class=\"fas fa-bars\"> </i>\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"hidden bg-white shadow-lg\" id=\"mobile-menu-dropdown\">\r\n");
      out.write("			<nav class=\"space-y-2 p-4\">\r\n");
      out.write("				<a class=\"block text-gray-700 hover:text-blue-500\" href=\"#welcome\">\r\n");
      out.write("					Home </a> <a class=\"block text-gray-700 hover:text-blue-500\"\r\n");
      out.write("					href=\"#about\"> About Us </a> <a\r\n");
      out.write("					class=\"block text-gray-700 hover:text-blue-500\"\r\n");
      out.write("					href=\"#popular-courses\"> Popular Courses </a> <a\r\n");
      out.write("					class=\"block text-gray-700 hover:text-blue-500\" href=\"#feedback\">\r\n");
      out.write("					Feedback </a>\r\n");
      out.write("				<div class=\"relative\">\r\n");
      out.write("					<input class=\"border border-gray-300 rounded-lg px-4 py-2 w-full\"\r\n");
      out.write("						placeholder=\"Explore...\" type=\"text\" />\r\n");
      out.write("					<button class=\"absolute right-0 top-0 mt-2 mr-2 text-gray-500\">\r\n");
      out.write("						<i class=\"fas fa-search\"> </i>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<button\r\n");
      out.write("					class=\"bg-red-500 text-white px-4 py-2 rounded-lg hover:bg-red-600 w-full\">\r\n");
      out.write("					Logout</button>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<script>\r\n");
      out.write("		document.getElementById('mobile-menu-button').addEventListener('click',\r\n");
      out.write("				function() {\r\n");
      out.write("					var menu = document.getElementById('mobile-menu-dropdown');\r\n");
      out.write("					if (menu.classList.contains('hidden')) {\r\n");
      out.write("						menu.classList.remove('hidden');\r\n");
      out.write("					} else {\r\n");
      out.write("						menu.classList.add('hidden');\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write(" <head>\r\n");
      out.write("  <meta charset=\"utf-8\"/>\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"/>\r\n");
      out.write("  <title>\r\n");
      out.write("   Instructor Dashboard\r\n");
      out.write("  </title>\r\n");
      out.write("  <script src=\"https://cdn.tailwindcss.com\">\r\n");
      out.write("  </script>\r\n");
      out.write("  <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("window.history.forward(); // Forces forward navigation after login\r\n");
      out.write("window.onload = function () {\r\n");
      out.write("    history.pushState(null, null, document.URL);\r\n");
      out.write("    window.addEventListener('popstate', function () {\r\n");
      out.write("        history.pushState(null, null, document.URL);\r\n");
      out.write("    });\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("    function loadComponents() {\r\n");
      out.write("        // Load Navbar\r\n");
      out.write("       fetch(\"navbardashboard.html\")\r\n");
      out.write("            .then(response => response.text())\r\n");
      out.write("            .then(data => {\r\n");
      out.write("                document.getElementById(\"navbar-container\").innerHTML = data;\r\n");
      out.write("            })\r\n");
      out.write("            .catch(error => console.error(\"Error loading navbar:\", error));\r\n");
      out.write("  \r\n");
      out.write("        // Load Footer\r\n");
      out.write("        fetch(\"footer.html\")\r\n");
      out.write("            .then(response => response.text())\r\n");
      out.write("            .then(data => {\r\n");
      out.write("                document.getElementById(\"footer-container\").innerHTML = data;\r\n");
      out.write("            })\r\n");
      out.write("            .catch(error => console.error(\"Error loading footer:\", error));\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("    window.onload = loadComponents;\r\n");
      out.write("    */\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<div id=\"navbar-container\"></div>\r\n");
      out.write(" <body class=\"bg-gray-100\">\r\n");
      out.write("  <header class=\"bg-white shadow\">\r\n");
      out.write("\r\n");
      out.write("  </header>\r\n");
      out.write("  <main class=\"container mx-auto p-4\">\r\n");
      out.write("   <div class=\"bg-white p-6 rounded-lg shadow-lg\">\r\n");
      out.write("    <h2 class=\"text-2xl font-bold mb-4\">\r\n");
      out.write("     Instructor Dashboard\r\n");
      out.write("    </h2>\r\n");
      out.write("    <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\">\r\n");
      out.write("     <div class=\"bg-gray-50 p-4 rounded-lg shadow\">\r\n");
      out.write("      <h3 class=\"text-xl font-semibold mb-2\">\r\n");
      out.write("       Add New Course\r\n");
      out.write("      </h3>\r\n");
      out.write("      <form>\r\n");
      out.write("       <div class=\"mb-4\">\r\n");
      out.write("        <label class=\"block text-gray-700\">\r\n");
      out.write("         Course Image\r\n");
      out.write("        </label>\r\n");
      out.write("        <input accept=\"image/*\" class=\"w-full border border-gray-300 rounded-lg px-4 py-2\" type=\"file\"/>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"mb-4\">\r\n");
      out.write("        <label class=\"block text-gray-700\">\r\n");
      out.write("         Course Title\r\n");
      out.write("        </label>\r\n");
      out.write("        <input class=\"w-full border border-gray-300 rounded-lg px-4 py-2\" placeholder=\"Enter course title\" type=\"text\"/>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"mb-4\">\r\n");
      out.write("        <label class=\"block text-gray-700\">\r\n");
      out.write("         Course Description\r\n");
      out.write("        </label>\r\n");
      out.write("        <textarea class=\"w-full border border-gray-300 rounded-lg px-4 py-2\" placeholder=\"Enter course description\"></textarea>\r\n");
      out.write("       </div>\r\n");
      out.write("       <button class=\"bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600\">\r\n");
      out.write("        Add Course\r\n");
      out.write("       </button>\r\n");
      out.write("      </form>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"bg-gray-50 p-4 rounded-lg shadow\">\r\n");
      out.write("      <h3 class=\"text-xl font-semibold mb-2\">\r\n");
      out.write("       Upload Materials\r\n");
      out.write("      </h3>\r\n");
      out.write("      <form>\r\n");
      out.write("       <div class=\"mb-4\">\r\n");
      out.write("        <label class=\"block text-gray-700\">\r\n");
      out.write("         Select Course\r\n");
      out.write("        </label>\r\n");
      out.write("        <select class=\"w-full border border-gray-300 rounded-lg px-4 py-2\">\r\n");
      out.write("         <option>\r\n");
      out.write("          Course 1\r\n");
      out.write("         </option>\r\n");
      out.write("         <option>\r\n");
      out.write("          Course 2\r\n");
      out.write("         </option>\r\n");
      out.write("         <option>\r\n");
      out.write("          Course 3\r\n");
      out.write("         </option>\r\n");
      out.write("        </select>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"mb-4\">\r\n");
      out.write("        <label class=\"block text-gray-700\">\r\n");
      out.write("         Upload PDF\r\n");
      out.write("        </label>\r\n");
      out.write("        <input accept=\".pdf\" class=\"w-full border border-gray-300 rounded-lg px-4 py-2\" type=\"file\"/>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"mb-4\">\r\n");
      out.write("        <label class=\"block text-gray-700\">\r\n");
      out.write("         Upload Video\r\n");
      out.write("        </label>\r\n");
      out.write("        <input accept=\"video/*\" class=\"w-full border border-gray-300 rounded-lg px-4 py-2\" type=\"file\"/>\r\n");
      out.write("       </div>\r\n");
      out.write("       <button class=\"bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600\">\r\n");
      out.write("        Upload\r\n");
      out.write("       </button>\r\n");
      out.write("      </form>\r\n");
      out.write("     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"bg-white p-6 rounded-lg shadow-lg mt-6\">\r\n");
      out.write("    <h2 class=\"text-2xl font-bold mb-4\">\r\n");
      out.write("     My Courses\r\n");
      out.write("    </h2>\r\n");
      out.write("    <div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4\">\r\n");
      out.write("     <div class=\"bg-gray-50 p-4 rounded-lg shadow\">\r\n");
      out.write("      <img alt=\"Placeholder image for Course 1\" class=\"w-full h-32 object-cover mb-4\" height=\"200\" src=\"https://storage.googleapis.com/a1aa/image/ud4d14RfW6qCJoTcah7eYjQDiFAa0-JKN9iTMV4H5uQ.jpg\" width=\"300\"/>\r\n");
      out.write("      <h3 class=\"text-xl font-semibold mb-2\">\r\n");
      out.write("       Course 1\r\n");
      out.write("      </h3>\r\n");
      out.write("      <p class=\"text-gray-700 mb-4\">\r\n");
      out.write("       Description of Course 1\r\n");
      out.write("      </p>\r\n");
      out.write("      <div class=\"flex items-center mb-4\">\r\n");
      out.write("       <span class=\"text-yellow-500\">\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star-half-alt\">\r\n");
      out.write("        </i>\r\n");
      out.write("       </span>\r\n");
      out.write("       <span class=\"ml-2 text-gray-600\">\r\n");
      out.write("        4.5/5\r\n");
      out.write("       </span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <button class=\"bg-red-500 text-white px-4 py-2 rounded-lg hover:bg-red-600\">\r\n");
      out.write("       Delete\r\n");
      out.write("      </button>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"bg-gray-50 p-4 rounded-lg shadow\">\r\n");
      out.write("      <img alt=\"Placeholder image for Course 2\" class=\"w-full h-32 object-cover mb-4\" height=\"200\" src=\"https://storage.googleapis.com/a1aa/image/z8uMT5IKX7RwvHo4nTazXdn-iBriHXwDTnIWryNuDHU.jpg\" width=\"300\"/>\r\n");
      out.write("      <h3 class=\"text-xl font-semibold mb-2\">\r\n");
      out.write("       Course 2\r\n");
      out.write("      </h3>\r\n");
      out.write("      <p class=\"text-gray-700 mb-4\">\r\n");
      out.write("       Description of Course 2\r\n");
      out.write("      </p>\r\n");
      out.write("      <div class=\"flex items-center mb-4\">\r\n");
      out.write("       <span class=\"text-yellow-500\">\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("       </span>\r\n");
      out.write("       <span class=\"ml-2 text-gray-600\">\r\n");
      out.write("        5/5\r\n");
      out.write("       </span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <button class=\"bg-red-500 text-white px-4 py-2 rounded-lg hover:bg-red-600\">\r\n");
      out.write("       Delete\r\n");
      out.write("      </button>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"bg-gray-50 p-4 rounded-lg shadow\">\r\n");
      out.write("      <img alt=\"Placeholder image for Course 3\" class=\"w-full h-32 object-cover mb-4\" height=\"200\" src=\"https://storage.googleapis.com/a1aa/image/_Jx1qhhlbK3gxbuq4tSINIcSzfSYWZLp0ci1TB2AxBY.jpg\" width=\"300\"/>\r\n");
      out.write("      <h3 class=\"text-xl font-semibold mb-2\">\r\n");
      out.write("       Course 3\r\n");
      out.write("      </h3>\r\n");
      out.write("      <p class=\"text-gray-700 mb-4\">\r\n");
      out.write("       Description of Course 3\r\n");
      out.write("      </p>\r\n");
      out.write("      <div class=\"flex items-center mb-4\">\r\n");
      out.write("       <span class=\"text-yellow-500\">\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star-half-alt\">\r\n");
      out.write("        </i>\r\n");
      out.write("       </span>\r\n");
      out.write("       <span class=\"ml-2 text-gray-600\">\r\n");
      out.write("        4.5/5\r\n");
      out.write("       </span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <button class=\"bg-red-500 text-white px-4 py-2 rounded-lg hover:bg-red-600\">\r\n");
      out.write("       Delete\r\n");
      out.write("      </button>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"bg-gray-50 p-4 rounded-lg shadow\">\r\n");
      out.write("      <img alt=\"Placeholder image for Course 4\" class=\"w-full h-32 object-cover mb-4\" height=\"200\" src=\"https://storage.googleapis.com/a1aa/image/puAkkvsGIxWM3r08wSwW6HF_ywZ2zTWXjtgMn-HR6t4.jpg\" width=\"300\"/>\r\n");
      out.write("      <h3 class=\"text-xl font-semibold mb-2\">\r\n");
      out.write("       Course 4\r\n");
      out.write("      </h3>\r\n");
      out.write("      <p class=\"text-gray-700 mb-4\">\r\n");
      out.write("       Description of Course 4\r\n");
      out.write("      </p>\r\n");
      out.write("      <div class=\"flex items-center mb-4\">\r\n");
      out.write("       <span class=\"text-yellow-500\">\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("       </span>\r\n");
      out.write("       <span class=\"ml-2 text-gray-600\">\r\n");
      out.write("        5/5\r\n");
      out.write("       </span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <button class=\"bg-red-500 text-white px-4 py-2 rounded-lg hover:bg-red-600\">\r\n");
      out.write("       Delete\r\n");
      out.write("      </button>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"bg-gray-50 p-4 rounded-lg shadow\">\r\n");
      out.write("      <img alt=\"Placeholder image for Course 5\" class=\"w-full h-32 object-cover mb-4\" height=\"200\" src=\"https://storage.googleapis.com/a1aa/image/imc1B7kYH0tcfKqnmV40KQ-v5uHuhryjxrlhFKeuNmw.jpg\" width=\"300\"/>\r\n");
      out.write("      <h3 class=\"text-xl font-semibold mb-2\">\r\n");
      out.write("       Course 5\r\n");
      out.write("      </h3>\r\n");
      out.write("      <p class=\"text-gray-700 mb-4\">\r\n");
      out.write("       Description of Course 5\r\n");
      out.write("      </p>\r\n");
      out.write("      <div class=\"flex items-center mb-4\">\r\n");
      out.write("       <span class=\"text-yellow-500\">\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star-half-alt\">\r\n");
      out.write("        </i>\r\n");
      out.write("       </span>\r\n");
      out.write("       <span class=\"ml-2 text-gray-600\">\r\n");
      out.write("        4.5/5\r\n");
      out.write("       </span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <button class=\"bg-red-500 text-white px-4 py-2 rounded-lg hover:bg-red-600\">\r\n");
      out.write("       Delete\r\n");
      out.write("      </button>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"bg-gray-50 p-4 rounded-lg shadow\">\r\n");
      out.write("      <img alt=\"Placeholder image for Course 6\" class=\"w-full h-32 object-cover mb-4\" height=\"200\" src=\"https://storage.googleapis.com/a1aa/image/LYv2BCH0-cJhoQpaUkXjyJgAFaTocuzj4NLZC-UMKoA.jpg\" width=\"300\"/>\r\n");
      out.write("      <h3 class=\"text-xl font-semibold mb-2\">\r\n");
      out.write("       Course 6\r\n");
      out.write("      </h3>\r\n");
      out.write("      <p class=\"text-gray-700 mb-4\">\r\n");
      out.write("       Description of Course 6\r\n");
      out.write("      </p>\r\n");
      out.write("      <div class=\"flex items-center mb-4\">\r\n");
      out.write("       <span class=\"text-yellow-500\">\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("        <i class=\"fas fa-star\">\r\n");
      out.write("        </i>\r\n");
      out.write("       </span>\r\n");
      out.write("       <span class=\"ml-2 text-gray-600\">\r\n");
      out.write("        5/5\r\n");
      out.write("       </span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <button class=\"bg-red-500 text-white px-4 py-2 rounded-lg hover:bg-red-600\">\r\n");
      out.write("       Delete\r\n");
      out.write("      </button>\r\n");
      out.write("     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   </div>\r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Footer</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/YOUR_KIT_CODE.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <footer class=\"bg-gray-800 text-white py-8\">\r\n");
      out.write("        <div class=\"container mx-auto grid grid-cols-1 md:grid-cols-3 gap-8\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <h3 class=\"text-xl font-bold mb-4\">About Us</h3>\r\n");
      out.write("                <p class=\"text-gray-400\">We are dedicated to providing the best online learning experience for both instructors and students.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <h3 class=\"text-xl font-bold mb-4\">Quick Links</h3>\r\n");
      out.write("                <ul class=\"text-gray-400\">\r\n");
      out.write("                    <li class=\"mb-2\"><a class=\"hover:text-white\" href=\"#\">Home</a></li>\r\n");
      out.write("                    <li class=\"mb-2\"><a class=\"hover:text-white\" href=\"#\">Courses</a></li>\r\n");
      out.write("                    <li class=\"mb-2\"><a class=\"hover:text-white\" href=\"#\">About</a></li>\r\n");
      out.write("                    <li class=\"mb-2\"><a class=\"hover:text-white\" href=\"#\">Contact</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <h3 class=\"text-xl font-bold mb-4\">Contact Us</h3>\r\n");
      out.write("                <p class=\"text-gray-400 mb-2\"><i class=\"fas fa-envelope mr-2\"></i> info@pragnya.com</p>\r\n");
      out.write("                <p class=\"text-gray-400 mb-2\"><i class=\"fas fa-phone mr-2\"></i> +1 234 567 890</p>\r\n");
      out.write("                <p class=\"text-gray-400\"><i class=\"fas fa-map-marker-alt mr-2\"></i> 123 Pragnya Street, Education City, USA</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container mx-auto text-center mt-8\">\r\n");
      out.write("            <p>Â© 2023 Pragnya. All rights reserved.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("   document.getElementById('mobile-menu-button').addEventListener('click', function() {\r\n");
      out.write("            var menu = document.getElementById('mobile-menu-dropdown');\r\n");
      out.write("            if (menu.classList.contains('hidden')) {\r\n");
      out.write("                menu.classList.remove('hidden');\r\n");
      out.write("            } else {\r\n");
      out.write("                menu.classList.add('hidden');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("  </script>\r\n");
      out.write(" </body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
