/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2025-03-08 20:46:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class studashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\"/>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"/>\r\n");
      out.write("    <title>Student Dashboard</title>\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Roboto', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-100\">\r\n");
      out.write("<header class=\"bg-white shadow\">\r\n");
      out.write("    <div class=\"container mx-auto p-4 flex justify-between items-center\">\r\n");
      out.write("        <div class=\"flex items-center space-x-4\">\r\n");
      out.write("            <img alt=\"Pragnya logo with a stylized book and graduation cap\" class=\"h-12 w-12\" height=\"50\" src=\"https://storage.googleapis.com/a1aa/image/OAPPWoq-wkyX940tsfptddkkry4qQyb_bSeqhOjguxU.jpg\" width=\"50\"/>\r\n");
      out.write("            <h1 class=\"text-2xl font-bold\">Pragnya</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button class=\"bg-red-500 text-white px-4 py-2 rounded-lg hover:bg-red-600\">Logout</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<main class=\"container mx-auto p-4\">\r\n");
      out.write("    <div class=\"bg-white p-6 rounded-lg shadow-lg\">\r\n");
      out.write("        <h2 class=\"text-2xl font-bold mb-4\">My Enrolled Courses</h2>\r\n");
      out.write("        <div class=\"space-y-4\">\r\n");
      out.write("            <div class=\"bg-gray-50 p-4 rounded-lg shadow flex flex-col md:flex-row items-center\">\r\n");
      out.write("                <img alt=\"Placeholder image for Enrolled Course 1\" class=\"w-32 h-32 object-cover mb-4 md:mb-0 md:mr-4\" height=\"200\" src=\"https://storage.googleapis.com/a1aa/image/puAkkvsGIxWM3r08wSwW6HF_ywZ2zTWXjtgMn-HR6t4.jpg\" width=\"200\"/>\r\n");
      out.write("                <div class=\"flex-1 text-center md:text-left\">\r\n");
      out.write("                    <h3 class=\"text-xl font-semibold mb-2\">Enrolled Course 1</h3>\r\n");
      out.write("                    <p class=\"text-gray-700 mb-2\">Description of Enrolled Course 1</p>\r\n");
      out.write("                    <div class=\"w-full bg-gray-200 rounded-full h-1.5 mb-4\">\r\n");
      out.write("                        <div class=\"bg-blue-500 h-1.5 rounded-full\" style=\"width: 70%\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600 md:ml-4\" onclick=\"viewCourse('Enrolled Course 1', 'Description of Enrolled Course 1', 'https://www.youtube.com/embed/dQw4w9WgXcQ')\">View Course</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"bg-gray-50 p-4 rounded-lg shadow flex flex-col md:flex-row items-center\">\r\n");
      out.write("                <img alt=\"Placeholder image for Enrolled Course 2\" class=\"w-32 h-32 object-cover mb-4 md:mb-0 md:mr-4\" height=\"200\" src=\"https://storage.googleapis.com/a1aa/image/imc1B7kYH0tcfKqnmV40KQ-v5uHuhryjxrlhFKeuNmw.jpg\" width=\"200\"/>\r\n");
      out.write("                <div class=\"flex-1 text-center md:text-left\">\r\n");
      out.write("                    <h3 class=\"text-xl font-semibold mb-2\">Enrolled Course 2</h3>\r\n");
      out.write("                    <p class=\"text-gray-700 mb-2\">Description of Enrolled Course 2</p>\r\n");
      out.write("                    <div class=\"w-full bg-gray-200 rounded-full h-1.5 mb-4\">\r\n");
      out.write("                        <div class=\"bg-blue-500 h-1.5 rounded-full\" style=\"width: 50%\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600 md:ml-4\" onclick=\"viewCourse('Enrolled Course 2', 'Description of Enrolled Course 2', 'https://www.youtube.com/embed/dQw4w9WgXcQ')\">View Course</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"bg-gray-50 p-4 rounded-lg shadow flex flex-col md:flex-row items-center\">\r\n");
      out.write("                <img alt=\"Placeholder image for Enrolled Course 3\" class=\"w-32 h-32 object-cover mb-4 md:mb-0 md:mr-4\" height=\"200\" src=\"https://storage.googleapis.com/a1aa/image/LYv2BCH0-cJhoQpaUkXjyJgAFaTocuzj4NLZC-UMKoA.jpg\" width=\"200\"/>\r\n");
      out.write("                <div class=\"flex-1 text-center md:text-left\">\r\n");
      out.write("                    <h3 class=\"text-xl font-semibold mb-2\">Enrolled Course 3</h3>\r\n");
      out.write("                    <p class=\"text-gray-700 mb-2\">Description of Enrolled Course 3</p>\r\n");
      out.write("                    <div class=\"w-full bg-gray-200 rounded-full h-1.5 mb-4\">\r\n");
      out.write("                        <div class=\"bg-blue-500 h-1.5 rounded-full\" style=\"width: 80%\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600 md:ml-4\" onclick=\"viewCourse('Enrolled Course 3', 'Description of Enrolled Course 3', 'https://www.youtube.com/embed/dQw4w9WgXcQ')\">View Course</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div id=\"courseModal\" class=\"fixed z-10 inset-0 overflow-y-auto hidden\">\r\n");
      out.write("    <div class=\"flex items-center justify-center min-h-screen px-4\">\r\n");
      out.write("        <div class=\"bg-white rounded-lg shadow-lg overflow-hidden w-full max-w-2xl relative\">\r\n");
      out.write("            <button id=\"closeButton\" class=\"absolute top-2 right-2 text-red-500 hover:text-red-700\" onclick=\"closeModal()\">\r\n");
      out.write("                <i class=\"fas fa-times fa-2x\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"p-4\">\r\n");
      out.write("                <h3 id=\"modalCourseName\" class=\"text-xl font-semibold mb-2\"></h3>\r\n");
      out.write("                <p id=\"modalCourseDescription\" class=\"text-gray-700 mb-4\"></p>\r\n");
      out.write("                <div class=\"aspect-w-16 aspect-h-9 mb-4\">\r\n");
      out.write("                    <iframe id=\"modalCourseVideo\" class=\"w-full h-full\" src=\"\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"space-y-4\">\r\n");
      out.write("                    <div class=\"bg-gray-50 p-4 rounded-lg shadow\">\r\n");
      out.write("                        <h4 class=\"text-lg font-semibold mb-2\">Module 1</h4>\r\n");
      out.write("                        <p class=\"text-gray-700 mb-2\">Description of Module 1</p>\r\n");
      out.write("                        <div class=\"w-full bg-gray-200 rounded-full h-1.5 mb-4\">\r\n");
      out.write("                            <div class=\"bg-blue-500 h-1.5 rounded-full\" style=\"width: 60%\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button class=\"bg-green-500 text-white px-4 py-2 rounded-lg hover:bg-green-600\">Download Video</button>\r\n");
      out.write("                        <button class=\"bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600 ml-2\">Download Materials</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bg-gray-50 p-4 rounded-lg shadow\">\r\n");
      out.write("                        <h4 class=\"text-lg font-semibold mb-2\">Module 2</h4>\r\n");
      out.write("                        <p class=\"text-gray-700 mb-2\">Description of Module 2</p>\r\n");
      out.write("                        <div class=\"w-full bg-gray-200 rounded-full h-1.5 mb-4\">\r\n");
      out.write("                            <div class=\"bg-blue-500 h-1.5 rounded-full\" style=\"width: 40%\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button class=\"bg-green-500 text-white px-4 py-2 rounded-lg hover:bg-green-600\">Download Video</button>\r\n");
      out.write("                        <button class=\"bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600 ml-2\">Download Materials</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bg-gray-50 p-4 rounded-lg shadow\">\r\n");
      out.write("                        <h4 class=\"text-lg font-semibold mb-2\">Module 3</h4>\r\n");
      out.write("                        <p class=\"text-gray-700 mb-2\">Description of Module 3</p>\r\n");
      out.write("                        <div class=\"w-full bg-gray-200 rounded-full h-1.5 mb-4\">\r\n");
      out.write("                            <div class=\"bg-blue-500 h-1.5 rounded-full\" style=\"width: 80%\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button class=\"bg-green-500 text-white px-4 py-2 rounded-lg hover:bg-green-600\">Download Video</button>\r\n");
      out.write("                        <button class=\"bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600 ml-2\">Download Materials</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"p-4 text-right\">\r\n");
      out.write("                <button class=\"bg-red-500 text-white px-4 py-2 rounded-lg hover:bg-red-600\" onclick=\"closeModal()\">Close</button>\r\n");
      out.write("                <button class=\"bg-gray-500 text-white px-4 py-2 rounded-lg hover:bg-gray-600 ml-2\" onclick=\"closeModal()\">Back</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function viewCourse(courseName, courseDescription, videoUrl) {\r\n");
      out.write("        document.getElementById('modalCourseName').innerText = courseName;\r\n");
      out.write("        document.getElementById('modalCourseDescription').innerText = courseDescription;\r\n");
      out.write("        document.getElementById('modalCourseVideo').src = videoUrl;\r\n");
      out.write("        document.getElementById('courseModal').classList.remove('hidden');\r\n");
      out.write("        window.addEventListener('scroll', moveCloseButton);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function closeModal() {\r\n");
      out.write("        document.getElementById('modalCourseVideo').src = \"\";\r\n");
      out.write("        document.getElementById('courseModal').classList.add('hidden');\r\n");
      out.write("        window.removeEventListener('scroll', moveCloseButton);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function moveCloseButton() {\r\n");
      out.write("        const closeButton = document.getElementById('closeButton');\r\n");
      out.write("        const scrollY = window.scrollY;\r\n");
      out.write("        closeButton.style.top = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${scrollY + 10}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("px`;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
